### ISSUE TITLE
[BUG] Default GlobalSign Timestamp is wrong

### ISSUE THREAD

**Issue by JohnPlanetary** [GlitchedPolygons/SigntoolGUI#3]
**Describe the bug**
When I click on "GlobalSign" it will enter: http://timestamp.globalsign.com/scripts/timstamp.dll into the Timestamp server.

**To Reproduce**
1. Go to 'Settings'
2. Click on 'GlobalSign'
3. It will appear the wrong (old) URL: "http://timestamp.globalsign.com/scripts/timstamp.dll" on the Timestamp server.

**Expected behavior**
Should enter: http://timestamp.globalsign.com/tsa/r6advanced1
That is the current modern URL.

**Desktop (please complete the following information):**
 - OS: Window 10 Home

**Comment by GlitchedPolygons** [comment]
@JohnPlanetary ah, good catch! Thanks for reporting this. Will fix this soon 👍🏻

**Comment by JohnPlanetary** [comment]
Thanks for the fast answer!
I also suggest Symantec TimeStamp in another topic but I remove the suggestion since that service as been discontinued in the end of last month and I didn't notice the change until now.

**Comment by GlitchedPolygons** [comment]
@JohnPlanetary yeah I saw it, thanks :) 

packaging release 1.2.0 right now.. Thank you again for the report  👍

**Comment by JohnPlanetary** [comment]
I've notice that Microsoft has their Time Stamp server available at:
http://timestamp.acs.microsoft.com

It is working.
Maybe also add these one?

**Comment by GlitchedPolygons** [comment]
@JohnPlanetary I was not aware of that one. Thanks so much for contributing to Signtool GUI :)

Will be in 1.3.0 for sure 👍
